name: Sync PR Labels with Issue
on:
  pull_request:
    types: [opened, edited, synchronized]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync Labels
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const prBody = pr.body || '';
            
            // Regular expression to find issue references
            const issueRegex = /#(\d+)/g;
            const matches = [...prBody.matchAll(issueRegex)];
            
            if (matches.length === 0) {
              console.log('No issue references found in PR description');
              return;
            }
            
            // Get the first referenced issue number
            const issueNumber = parseInt(matches[0][1]);
            
            try {
              // Get the referenced issue's labels
              const issue = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber
              });
              
              const issueLabels = issue.data.labels.map(label => label.name);
              
              if (issueLabels.length === 0) {
                console.log(`Issue #${issueNumber} has no labels`);
                return;
              }
              
              // Add the same labels to the PR
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                labels: issueLabels
              });
              
              console.log(`Successfully synced labels from issue #${issueNumber} to PR #${pr.number}`);
              
            } catch (error) {
              console.error('Error syncing labels:', error);
              core.setFailed(error.message);
            }
