name: Sync Labels to PR

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  sync_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install @octokit/rest @actions/github

      - name: Run Sync Labels Script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: node sync-labels.js
