name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Set up environment variables
      - name: Set environment variables
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: echo "Environment variable DATABASE_URL is set."

      # Install dependencies
      - name: Install dependencies
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm install

      # Run Prisma migrations (if needed)
      - name: Run Prisma migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy

      # Run tests
      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm test

      # Build the project
      - name: Build project
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build

      # Run lint checks
      - name: Run lint checks
        run: npm run lint
